spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&noAccessToProcedureBodies=true
        name: dev_biocloud_search
        username: dev_cloud
        password: dev_cloud.123
server:
    port: 8080